baseUrl: http://example.org/
languageCode: pt-br
title: Reisfmb blog
theme: smigle

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: Sobre
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categorias
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5

params:
  abbrDateFmt: "Jan 2"
  author: "Bruno Reis"
  brandIconFile: "images/mendelbrot.svg"
  dateFmt: "02/01/2006"
  customStylesheets:
    - "css/custom.css"
  social:
    - name: GitHub
      url: https://github.com/reisfmb
    - name: breisfm@gmail.com
      url: mailto:breisfm@gmail.com
  subtitle: "Bruno Reis Ferreira Maia"